# Generated by Django 4.1.7 on 2023-03-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Service Date')),
                ('service', models.CharField(choices=[('R', 'Restringing'), ('I', 'Intonation'), ('D', 'Detailing')], default='R', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='guitar',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
