# Generated by Django 4.1.7 on 2023-03-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maintenence_alter_guitar_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintenence',
            new_name='Maintenance',
        ),
    ]
