# Generated by Django 4.1.7 on 2023-03-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_maintenence_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(),
        ),
    ]
